steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'github.com/maxhawkins/transitdb/cmd/transitdb']
  env: ['PROJECT_ROOT=github.com/maxhawkins/transitdb', 'CGO_ENABLED=0']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/transitdb:latest', '--tag=gcr.io/$PROJECT_ID/transitdb:$COMMIT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/transitdb:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/transitdb:latest']
